---
AllCops:
  DisplayCopNames:    true
  DisplayStyleGuide:  true
  StyleGuideCopsOnly: true
  TargetRubyVersion:  2.3

Style/Alias:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/FileName:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# Settings for Struct#hashify

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/AbcSize:
  Max: 17.12

Metrics/MethodLength:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 8
